name: Publish SporeModder FX Release
on: push
  #workflow_dispatch:

jobs:
  build_smfx:
    name: Build SporeModder-FX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SporeModder-FX
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate release version
        id: version_number
        run: |
          version=$( bash calculate_new_version.sh )
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Build with Maven
        run: mvn -B -Drevision="${{ steps.version_number.outputs.version }}" package --file pom.xml

      - name: Upload build
        uses: actions/upload-artifact@v3.1.3
        with:
          name: SporeModder-FX-jar
          path: shade/sporemodderfx.jar
          
  publish_release:
    name: Publish Release
    needs: build_smfx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SporeModder-FX
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: version_number
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --oneline --format=%s > changelog.txt
          version=$( bash calculate_new_version.sh )
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: SporeModder-FX-jar

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: SporeModder FX v${{ steps.version_number.outputs.version }}
          tag_name: v${{ steps.version_number.outputs.version }}
          body_path: changelog.txt
          files: |
            sporemodderfx.jar
